build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
    - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%

test_script:
    - python make.py
    - python make.py clean
    - python make.py help
