build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
    - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%

test_script:
    - python make.py
    - python make.py clean
    - python make.py help
